### ISSUE TITLE
Filter expectations when clearing

### ISSUE THREAD

**Issue by khanh-nguyen** [jamesdbloom/mockserver#139]
I tried to filter expectations when clearing them like this:
```
yield client.clear({
		httpRequest: {
				path: '.*',
				cookies: [
						{
								name: cookie.name,
								value: cookie.value
						}
				]
		}
});
```
but Mockserver log shows:
```
INFO o.m.m.MockServerHandler clearing expectations and request logs that match:

	null
```
Is it possible to clear only expectations that match certain conditions?

**Comment by jamesdbloom** [comment]
that looks like javascript, are you using the `mockServeClient.js` file or `mockserver-client-node` npm module?

Both of these `clear` functions only currently support providing the path to clear on as follows:
```js
client.clear('/somePath');
```

I could however extend this if required, so that the clear function supports a path or request matcher.

**Comment by khanh-nguyen** [comment]
I'm using `mockserver-client-node

**Comment by jamesdbloom** [comment]
https://github.com/jamesdbloom/mockserver-client-node/commit/a5772a5bc8d13050886748ece12d1eb86ef30d50

I have added this support to both javascript clients (see mockserver-client-node 1.0.6) so I'm going to close this issue.

**Comment by khanh-nguyen** [comment]
Cool. Thanks a lot for your quick response. I'll try very soon.

**Comment by khanh-nguyen** [comment]
Working great for me. Thank you very much, @jamesdbloom.
