### ISSUE TITLE
Record traffic between browser and server

### ISSUE THREAD

**Issue by rtalexander** [jamesdbloom/mockserver#148]
Is it possible to use MockServer Proxy (MSP) to record the HTTP requests and responses from a browser (e.g., Chrome) and a web server, all from the command line? If so, what are the command line arguments (or procedure) for setting this up?

Thanks,

Roger Alexander.

**Comment by jamesdbloom** [comment]
Yes it is possible.  

There are multiple ways to run the MockServer depending on your environment.  If you using a mac then homebrew is probably the easiest way to do it:
1. install MockServer using hoembrew `brew install mockserver`
2. run MockServer `mockserver -proxyPort 1090`
3. turn on SOCK proxying using System Preferences -> Network -> Advanced -> Proxies -> SOCKS Proxy (enter 127.0.0.1 for host and 1090 for port)

This will capture all traffic on my machine at the sock level.  This will capture traffic from the browser for example but will also capture traffic from your email client, etc.  To filter out only the requests you are interested you can use the `/dumpToLog` endpoint as follows:

`curl 'http://localhost:1080/dumpToLog' -X PUT --data "{'path': '/somePath'}"`

This will create a file called `mockserver_request.log` in the directory you started the mockserver process (unless you provided the override setting to specify the logging directory).

There are numerous other ways to to run the MockServer all of which will behave in the same way once it is running.  To see full details of how to run the Mockserver see: http://www.mock-server.com/proxy/running_mock_server_proxy.html

For more details about to configure you browser to use the proxy see: http://www.mock-server.com/proxy/configuring_clients.html#ajax-on-mac 

Also please note this exact version has a small issue with the certificate generation due to a mutli-threading error.  This is now fixed but I have not yet released the fix.  I will do that this weekend after which time the issue should go away, however it will take some more time to get the version in homebrew updated (thats why I haven't added the details of homebrew to the website yet).
