### ISSUE TITLE
Check for absence of header not working

### ISSUE THREAD

**Issue by akloeber** [jamesdbloom/mockserver#159]
I'm trying to verify that a specific header (`Authorization` in this case) is not present in the request and already tried the following:

    withHeader(NottableString.not("Authorization"))
    withHeader(NottableString.string("Authorization"), NottableString.not(".*"))

The following gives the right result but I'm not sure if this is only a coincidence because I did not find anything in the documentation about how to use `NottableString`:

    withHeader(NottableString.not("Authorization"), NottableString.string(".*"))

__Environment:__
Java 1.7.0_79
mockserver-netty 3.9.17

**Comment by jamesdbloom** [comment]
As soon as I get a chance I'll look into this, likely in the next week or so.

**Comment by jamesdbloom** [comment]
I am in the process of updating and extending the documentation.  The `not` logic is on the documentation list.

You are correct as follows.

```java
withHeader(NottableString.not("Authorization"))
```

Matches any header that does not have the name "Authorization" and has no values.  It seems like this match always passes, I will look into this but I suspect its because a head with no values is a little strange.

```java
withHeader(NottableString.string("Authorization"), NottableString.not(".*"))
```

Matches any header with a name "Authorization" but a value that does not match `.*` this is an impossibility since `.*` regex will match any string.  So this expression with will never match.

```java
withHeader(NottableString.not("Authorization"), NottableString.string(".*"))
```

Matches if there is no header with a name "Authorisation" that has any value.  I think this is exactly what you are looking for.

I will improve the documentation and while doing try to see if there is any way I can make the `not` logic a little simpler.
