### ISSUE TITLE
Support expectation initialiser for all versions (not just maven plugin)

### ISSUE THREAD

**Issue by ulag** [jamesdbloom/mockserver#170]
We are exploring mock server for our automated tested infrastructure and it looks great. One issue we have is, we would like to run the mock server on an  AWS EC2 instance behind an elastic load balancer. The AWS Elastic Load balancer does a health check on the instance with a "GET" http calls only. Mock server seem to have "PUT" request to check status. Is it possible to add a status api on "GET" verb as well? if the concern is that this may come in the way of actual test expectations, may be have a private GET api like /__status (slash-underscore-underscore-status) or some thing like that?

any guidance on this would be greatly appreciated.

**Comment by jamesdbloom** [comment]
Sorry for the delay I've been backed up lately.

How are you running MockServer?  The reason I ask is that it would be possible to start up the MockServer with a pre-canned expectation already setup but only when running via maven.  Using this approach you could add a pre-canned expectation for the status endpoint using an initializationClass (see http://www.mock-server.com/mock_server/running_mock_server.html#maven_plugin).

As you pointed out my concern with adding a status endpoint is that this could get in the way of endpoints people are trying to write an expectation for even if I used an underscore to indicate a private / internal endpoint.

I would be happy to extend the concept of an initializationClass beyond the maven plugin and move that logic into the core MockServer so that it could be used which away way the MockServer was run.  Then all you would need to do is to create a class that implemented a simple interface which as soon as the MockServer started would setup an expectation (in this case for a status endpoint).  Would that be helpful?

**Comment by ulag** [comment]
we are just using the vanilla  docker container without any changes. we have ruby environment and aren't setup to do java dev. But if thats the only way, we could look at writing our own initializer class.
is there any other startup hook that we can use to set up pre-canned response for status check

**Comment by fhueter** [comment]
Just want to say that I would appreciate a GET /__status default expectation within the mockserver-war package as well. cargo-maven2-plugin does not support any PUT ping requests as well but I really need them to stabilize my build. At the moment I do not see any chance to use the pre-canned expactations you were talking about above when using mockserver-war, so this change would be really helpful.

**Comment by jamesdbloom** [comment]
I feel uncomfortable about doing that because that would prevent anyone from mocking that call.

However, I do agree in your case a standard way to setup pre-canned expectations would be ideal.  I would be happy to add a mechanism to do that using a JSON file which lists all the pre-canned expectations.  I'll look into that as it shouldn't be a massive job.  I expect I could have that fix ready roughly in the next week or so.

**Comment by fhueter** [comment]
This seems to be a good idea to avoid any problems with pre-defined URL patterns. Thanks in advance for your quick feedback and even an extension of the existing code for resolving this feature request.

**Comment by jamesdbloom** [comment]
FYI - As soon as I complete the work on websocket support mentioned in the last comment on #280 I will implement the support for pre-canned expectations and release both in a new release (along with a couple of other fixes).

**Comment by simondiep** [comment]
Has there been any progress on this?
I am really interested in this feature.

**Comment by jamesdbloom** [comment]
implemented solution and documentation will be available in next release
