### ISSUE TITLE
Strict Matching (only match the exact expectation)

### ISSUE THREAD

**Issue by jamesdbloom** [jamesdbloom/mockserver#180]
this issues should encompass the use cases identified in: 
#178 - Strict Query String Matching?
#76 - Duplicate request parameters should cause verification errors.
#75 - Allow tests to specify relaxed or strict header matching.
#88 - Allow users to specify that an HttpHeader in an expectation is strict or otherwise.

**Comment by nima200** [comment]
Seeing as this was an open issue in 2015, is it now possible to have the functionality mentioned in #178 somehow?
I am struggling with the case where I want to send different responses when i get

`?action=CLUSTERSTATUS`
vs
`?action=CLUSTERSTATUS&wt=json`

As you can imagine, I am mocking a service which specifies whether the result is json or not in the query params instead of content type and I need to find a way to verify that and send different responses in the body accordingly.

**Comment by vitalybe** [comment]
@nima200 I've had the same issue. While waiting for a proper solution, what worked for me was to reorder the expectations:

Put the longer expectations (the ones with more matched parameters) first and the shorter one after.

**Comment by jamesdbloom** [comment]
The other option is to use the `not` operator: http://mock-server.com/mock_server/creating_expectations.html#button_match_request_by_not_matching_body_with_xpath

**Comment by jamesdbloom** [comment]
new feature requests now prioritised on Trello, so closing issue in GitHub, only bugs or unaccepted feature requests will stay in GitHub, so that new feature can be more effectively managed, see: https://trello.com/c/ZA0bOLug/15-strict-exact-matching
