### ISSUE TITLE
mockserver-client-scala

### ISSUE THREAD

**Issue by Unisay** [jamesdbloom/mockserver#187]
Hi James,

JFYI: I wrote it on weekend: https://github.com/Unisay/mockserver-client-scala

If you're interested in incorporating it into the mockserver repo - let me know.

**Comment by jamesdbloom** [comment]
I had decided not implemented a scala client because scala runs on the JVM so the existing Java client should be available for anyone using scala to use.  There are currently a number of scala projects I know using the Java client, however, is there something in the scala client you implemented that makes it nicer to use in scala, if so perhaps the java client could be extended to support that feature?

Thanks,

James

**Comment by Unisay** [comment]
> There are currently a number of scala projects I know using the Java client

Java client can be used from Scala, true. 

However, there is something in the Scala client I implemented that makes it nicer to use in Scala - it is `DSL` that utilises Scala language features (singleton objects, infix method notation, implicit conversions, etc.) 

Its better to compare by example:

## Java (used from scala)
```
val client = ClientAndServer.startClientAndServer(8080)

client
  .when(mockRequest()
      .withPath("/path")
      .withMethod("POST")
      .withHeader("Content-Type", "text/plain")
      .withQueryStringParameter("key", "value"))
  .respond(mockResponse()
      .withStatusCode(200)
      .withBody("Response body"))
```

## Scala (one-liner)
```
implicit val client = ClientAndServer.startClientAndServer(8080)

when post "/path" has ContentType("text/plain") + param("key", "value") respond Ok + "Response body"
```

## Scala (multi-liner)
```
implicit val client = ClientAndServer.startClientAndServer(8080)

when post "/path" has {
  ContentType("text/plain") and 
  param("key", "value") 
} respond {
  Ok and
 "Response body"
}
```

So the main added value is readability. 
Additional value is type-safety (predefined HTTP methods, common headers and HTTP statuses)

**Comment by jamesdbloom** [comment]
I agree that one line expectations is a nice feature.

I'm not trying to be awkward but I'm reluctant to add another client as there are currently eight separate clients that each require updating when ever the server side code changes.  Adding another two (MockServer & proxy) would still further increase the amount of code to make a new feature or refactor an existing feature.  Where a client adds support for a completely new language that does not already exist there is a case as the benefit could outweigh the cost, but currently in the case of Scala I don't personally believe this to be the case.

In addition I'm not sure that making the HTTP methods, common header and HTTP statuses type safe is required.  This is because the `io.netty.handler.codec.http` package already contains this and is part of the Java based client.  I wanted to avoid trying to duplicate this sort of logic.  It is also available numerous other libraries including from google, apache and spring etc.

**Comment by Unisay** [comment]
Thanks for your reasoning, which I fully understand and respect.

Since I am going to use Scala client DSL in my project at work anyway, here
is what I suggest:
I keep it in my Github repository
https://github.com/Unisay/mockserver-client-scala
I maintain it and make sure its compatible with the future versions so that
you don't have this burden for the little added value :)
You drop a link somewhere in the mock-server documentation saying that
there is a third party maintained Scala DSL.

If users find it useful with time - you can always revisit the decision.
What do you think, James?

**Comment by jamesdbloom** [comment]
I agree that sounds like a good plan.  In the next week I'll update the documentation with a link to your Scala client.
