### ISSUE TITLE
Provide version tags for docker images

### ISSUE THREAD

**Issue by marcust** [jamesdbloom/mockserver#195]
The docker images don't come with versioned tags, which makes it quite hard to always exactly know which version of mockserver is inside the image. Is it possible to provide proper version tags?

**Comment by jamesdbloom** [comment]
I have added one for the new release and going forward I will add them.  I can't add them for the history version because the history versions of the docker image dependent on a image of java that no longer exists so when I try to run the old versions using a tag the build fails.  Going forward this will be fixed though.

**Comment by jamesdbloom** [comment]
See https://hub.docker.com/r/jamesdbloom/mockserver/tags/ 

I also incorrectly created the mockserver-3.10.2 with mockserver-3.10.1 version but this will be fixed once I release the new version
