### ISSUE TITLE
HTTP/2

### ISSUE THREAD

**Issue by lpandzic** [jamesdbloom/mockserver#216]
Is it (or planned to be) supported?

**Comment by jamesdbloom** [comment]
There is currently no support for HTTP/2 but this is on the TODO list

**Comment by glockhart** [comment]
has there been any movement on HTTP/2 support?

**Comment by jlojosnegros** [comment]
Any update regarding http/2 support?

**Comment by jamesdbloom** [comment]
Support for HTTP/2 is not likely to be available soon (i.e. within the next 3 months).

HTTP/2 support is particularly problematic in Java 8 or lower because it requires binary support due to ALPN.  This makes is very hard to support multiple OSes in a fully reliable way.  Although it is possible to work around this it does add considerable complexity.  As I understand Java 11 onwards has solved this issue, but not sure about Java 9/10.

A PR would be gratefully received.

**Comment by jamesdbloom** [comment]
new feature requests now prioritised on Trello, so closing issue in GitHub, only bugs or unaccepted feature requests will stay in GitHub, so that new feature backlog can be more effectively managed, see: https://trello.com/c/vLEEtk5o/16-support-http2

**Comment by ghilainm** [comment]
Is it supported now or planned to be supported?

**Comment by liuzengh** [comment]
Is it (or planned to be) supported?

**Comment by MSKDom** [comment]
Without this, it makes mock-server proxy functionality pointless. This completely breaks any use of it with modern backend systems as there's no way to enforce http 1.1/0.
