### ISSUE TITLE
Two Certificates are showing when mocking Https connection

### ISSUE THREAD

**Issue by nhatnguyen26** [jamesdbloom/mockserver#219]
I was using ```ClientAndServer.startClientAndServer(port);``` to start MockServer along with my unit tests class.
I was testing a HttpClient where it will allow SelfSignedCertificate to pass through. I was using Apache HttpClient also. To do that, I am required to use the ```TrustSelfSignedStrategy()``` to handle the strategy. If you are familiar with the sources, this check if the number of certificates is ```1```. 
But certificates from MockServer is actually 2, for instance: ```Subject: C=UK, ST=England, L=London, O=MockServer, CN=www.mockserver.com``` and ```Subject: C=UK, ST=England, L=London, O=MockServer, CN=localhost```. Is there any way to go around this and only use one certificate?

**Comment by jamesdbloom** [comment]
The reason there are two certificates appearing is because there is a certificate chain.  The MockServer has a certificate authority certificate that is used to sign all dynamically created certificates.  In the case you show `Subject: C=UK, ST=England, L=London, O=MockServer, CN=www.mockserver.com` is the MockServer certificate authority certificate, whereas `Subject: C=UK, ST=England, L=London, O=MockServer, CN=localhost` is the actual certificate.  Notice the common name, the certificate authority certificate has a common name of **www.mockserver.com** whereas the dynamically created certificate has a common name of **localhost** because you are making a request to the **localhost** domain.

Certificate Authority Certificate:

<img width="496" alt="ca_certificate" src="https://cloud.githubusercontent.com/assets/733179/13541654/876aedf6-e255-11e5-8f3e-ca4f30673687.png">

localhost Certificate (signed by certificate above):

<img width="496" alt="localhost_certificate" src="https://cloud.githubusercontent.com/assets/733179/13541666/9c4c2992-e255-11e5-9f68-0de0d7c6af46.png">

To resolve this and enable java to use any MockServer signed certifcate the JVM needs to treat the MockServer CA certificate as a trusted certificate authority.  The following script should show you how to do this: https://github.com/jamesdbloom/mockserver/blob/master/scripts/install_ca_certificate.sh.  I have only tested this script on a mac so I can't guarantee it'll work on other OSes but it should demonstrate the steps you need to take.

I am going to close this ticket as it is not a issue with MockServer, if you need more information please feel free to open this ticket.
