### ISSUE TITLE
Cannot configure number of threads to concurrently serve requests

### ISSUE THREAD

**Issue by tashoyan** [jamesdbloom/mockserver#235]
It seems, mock-server processes all requests in one thread. Real web server should process incoming requests in multiple threads. Would be good to have the ability to test an application against a multi-threaded server.
From mock-server code one can find, that Netty server configuration is hardcoded, so there is no chance to configure the number of server threads:

public class MockServer implements Stoppable {
...
    private final EventLoopGroup bossGroup = new NioEventLoopGroup();
    private final EventLoopGroup workerGroup = new NioEventLoopGroup();

**Comment by morphysk** [comment]
+1 that will be great

**Comment by tashoyan** [comment]
Finally, I have come up with an alternate implementation that supports tests with multiple threads: https://github.com/tashoyan/httpspy

**Comment by jamesdbloom** [comment]
Why would you need to increase the number of threads? 

Do you have a specific scenario where you have evidence that adding more threads will increase throughput?

`new NioEventLoopGroup()` does use multiple threads, in fact it uses the default multi-thread configuration from Netty.  In this configuration the number of threads is 2 * the number of CPU cores.  Please don't forgot that adding threads does not necessarily lead to higher performance.  In fact there are many scenarios where this would reduce performance due to the amount of thread scheduling.  This is why the Netty default is 2 * the number of CPU cores.

**Comment by tashoyan** [comment]
I need the possibility to _configure_ the number of threads in the mock server. What if my client issues a great number of concurrent requests and overloads the server? I may want to implement custom logic in my client: for example, try to reattempt failed requests when the load decreases. If reattempts failed N times for a request, then redirect this request to some special channel. To test such scenarios I need the configurable number of threads in the mocking server.

**Comment by jamesdbloom** [comment]
As I understand your trying to push MockServer until it fails to test how your application responds to those failures

I would suggest if you want to test for response to failure scenarios try using `HttpError` for example:

```java
mockServerClient
        .when(
                request()
        )
        .error(
                error()
                        .withDropConnection(true)
                        .withResponseBytes("some_random_bytes".getBytes())
        );
```

Or try using `ConnectionOptions` for example:

```java
mockServerClient
        .when(
                request()
        )
        .respond(
                response()
                        .withBody(binary("some_long_body".getBytes()))
                        .withHeader(HttpHeaders.CONTENT_TYPE, MediaType.ANY_AUDIO_TYPE.toString())
                        .withConnectionOptions(
                                connectionOptions()
                                        .withCloseSocket(true)
                                        .withSuppressContentLengthHeader(true)
                        )
        );
```

Or just use `Delay` for example:

```java
mockServerClient
        .when(
                request()
                        .withPath(calculatePath("some_path1"))
        )
        .respond(
                response()
                        .withBody("some_body1")
                        .withDelay(new Delay(TimeUnit.MILLISECONDS, 10))
        );
```

The reason I suggest this as I ran some scalability test through MockServer and managed to get extremely high throughputs, in fact the main bottleneck is non-native SSL handling within Netty due to synchronisation.  Adding more Threads only makes this problem worse because there are more Threads contending for the same synchronised resource.  Unfortunately this is the way the JVM SSL works and it is only possible to improve this by using native libraries.  However, if these are used then this make the application CPU dependent.  

For the full figures from a previous set of tests that show this are as follows:

**HTTP:**

**10,000 requests** run by **100 concurrent clients**

```bash
Jamess-MacBook-Pro-2:~ jamesdbloom$ ab -n 10000 -c 100 http://localhost:1080/simple
This is ApacheBench, Version 2.3 <$Revision: 1663405 $>
Copyright 1996 Adam Twiss, Zeus Technology Ltd, http://www.zeustech.net/
Licensed to The Apache Software Foundation, http://www.apache.org/

Benchmarking localhost (be patient)
Completed 1000 requests
Completed 2000 requests
Completed 3000 requests
Completed 4000 requests
Completed 5000 requests
Completed 6000 requests
Completed 7000 requests
Completed 8000 requests
Completed 9000 requests
Completed 10000 requests
Finished 10000 requests


Server Software:        
Server Hostname:        localhost
Server Port:            1080

Document Path:          /simple
Document Length:        13 bytes

Concurrency Level:      100
Time taken for tests:   2.877 seconds
Complete requests:      10000
Failed requests:        0
Total transferred:      970000 bytes
HTML transferred:       130000 bytes
Requests per second:    3476.28 [#/sec] (mean)
Time per request:       28.766 [ms] (mean)
Time per request:       0.288 [ms] (mean, across all concurrent requests)
Transfer rate:          329.30 [Kbytes/sec] received

Connection Times (ms)
              min  mean[+/-sd] median   max
Connect:        0    1   1.3      0     110
Processing:     2   28  15.9     26     166
Waiting:        2   28  15.9     26     166
Total:          3   29  15.8     27     167

Percentage of the requests served within a certain time (ms)
  50%     27
  66%     33
  75%     36
  80%     39
  90%     45
  95%     50
  98%     57
  99%     66
 100%    167 (longest request)
```

**HTTPS:**

**10,000 requests** run by **100 concurrent clients**

```bash
Jamess-MacBook-Pro-2:~ jamesdbloom$ ab -n 10000 -c 100 -Z 'AES128-SHA' https://localhost:1080/simple
This is ApacheBench, Version 2.3 <$Revision: 1663405 $>
Copyright 1996 Adam Twiss, Zeus Technology Ltd, http://www.zeustech.net/
Licensed to The Apache Software Foundation, http://www.apache.org/

Benchmarking localhost (be patient)
Completed 1000 requests
Completed 2000 requests
Completed 3000 requests
Completed 4000 requests
Completed 5000 requests
Completed 6000 requests
Completed 7000 requests
Completed 8000 requests
Completed 9000 requests
Completed 10000 requests
Finished 10000 requests


Server Software:        
Server Hostname:        localhost
Server Port:            1080
SSL/TLS Protocol:       TLSv1,AES128-SHA,1024,128

Document Path:          /simple
Document Length:        13 bytes

Concurrency Level:      100
Time taken for tests:   241.512 seconds
Complete requests:      10000
Failed requests:        0
Total transferred:      970000 bytes
HTML transferred:       130000 bytes
Requests per second:    41.41 [#/sec] (mean)
Time per request:       2415.116 [ms] (mean)
Time per request:       24.151 [ms] (mean, across all concurrent requests)
Transfer rate:          3.92 [Kbytes/sec] received

Connection Times (ms)
              min  mean[+/-sd] median   max
Connect:      211 1576 432.3   1672    3583
Processing:     8  832 401.6    709    2802
Waiting:        5  397 314.2    394    1897
Total:       1578 2408 272.6   2352    5249

Percentage of the requests served within a certain time (ms)
  50%   2352
  66%   2393
  75%   2429
  80%   2457
  90%   2554
  95%   2811
  98%   3410
  99%   3797
 100%   5249 (longest request)
```

The SSL handling in Netty suffers significantly by concurrency so for a less concurrent test with 10,000 requests run by 10 concurrent clients the numbers are significantly better:

**HTTPS:**

**10,000 requests** run by **10 concurrent clients**

```bash
Jamess-MacBook-Pro-2:~ jamesdbloom$ ab -n 10000 -c 10 -Z 'AES128-SHA' https://localhost:1080/simple
This is ApacheBench, Version 2.3 <$Revision: 1663405 $>
Copyright 1996 Adam Twiss, Zeus Technology Ltd, http://www.zeustech.net/
Licensed to The Apache Software Foundation, http://www.apache.org/

Benchmarking localhost (be patient)
Completed 1000 requests
Completed 2000 requests
Completed 3000 requests
Completed 4000 requests
Completed 5000 requests
Completed 6000 requests
Completed 7000 requests
Completed 8000 requests
Completed 9000 requests
Completed 10000 requests
Finished 10000 requests


Server Software:        
Server Hostname:        localhost
Server Port:            1080
SSL/TLS Protocol:       TLSv1,AES128-SHA,1024,128

Document Path:          /simple
Document Length:        13 bytes

Concurrency Level:      10
Time taken for tests:   243.849 seconds
Complete requests:      10000
Failed requests:        0
Total transferred:      970000 bytes
HTML transferred:       130000 bytes
Requests per second:    41.01 [#/sec] (mean)
Time per request:       243.849 [ms] (mean)
Time per request:       24.385 [ms] (mean, across all concurrent requests)
Transfer rate:          3.88 [Kbytes/sec] received

Connection Times (ms)
              min  mean[+/-sd] median   max
Connect:       21  171  50.8    174     847
Processing:     1   73  35.5     68     705
Waiting:        1   49  36.1     43     616
Total:         40  244  62.6    239     894

Percentage of the requests served within a certain time (ms)
  50%    239
  66%    258
  75%    273
  80%    282
  90%    315
  95%    341
  98%    377
  99%    420
 100%    894 (longest request)
```

**Comment by prabjohns-atex** [comment]
Hi James, this is a feature that would help in certain test scenarios. ( I know because I just hit this ). I think I have a multi-threaded bug downstream of MockServer in our own code. I am trying to isolate this by writing an upstream Junit test case which generates lots of parallel requests and fires them at mock server and collecting the results. Unfortunately, it looks as though the requests are handled serially, so I'm not really testing it.

It looks as though the MockServerClient hard codes the number of threads as 4.

Where as I am calling with 32 threads.

I have with DELAY of two seconds set to simulate slow downstream responses.

In a real web server environment, all my responses (I generate 512) should complete in 32 seconds approx.

**Comment by tashoyan** [comment]
@prabjohns-atex did you have a chance to try [httpspy](https://github.com/tashoyan/httpspy)? It provides the ability to configure the number of servicing threads (despite it is old).

**Comment by prabjohns-atex** [comment]
> @prabjohns-atex did you have a chance to try [httpspy](https://github.com/tashoyan/httpspy)? It provides the ability to configure the number of servicing threads (despite it is old).

Thanks for the suggestion.

I worked around it for now - this is only an ad-hoc debugging test, so I just removed the delay temporarily.
