### ISSUE TITLE
Can I intercept only a match request and let the the non-match requests passthrough

### ISSUE THREAD

**Issue by lucrib** [jamesdbloom/mockserver#248]
Is it possible to create a local mock server/proxy where I can set some expectations, and intercept only these, and the let the non-match passthrough?

This would be interesting, them I would be able to test Desktop applications, intercepting only the selected requests and let the other local requests to passthrough (like Continuous Integration Server).

**Comment by nxone** [comment]
i have the same issues.
did you solved it ? @lucasribeiro1990

**Comment by lucrib** [comment]
No. Did not solve that yet. :disappointed:

**Comment by jamesdbloom** [comment]
It is possible to do this. You would need to setup two expectations, one that match all request which should be setup first. This first expectation should be setup to forward all request onwards using a forward action. The second expectation should only match the specific request you want to mock and this should be setup with a response action.

Tricky part will be if you have multiple requests going to multiple domains and ports because that would be hard to do in a forward action, however it would be possible using multiple expectations each with a forward action that match on domain name.

The point to consider is if your application is attempting to send requests to multiple ports and domains. The MockServer would need to receive all these requests. I would suggest the best way to do would be to bind the MockServer to all required ports on your local machine (or any other required non local IP address) then edit your hosts file (check google for help on that) to bind each host name you want to sent through the MockServer to the IP address MockServer is running on (if running locally that would be 127.0.0.1).

I think this should meet your needs. Please let me know if this makes sense to you as I'love close this ticket in a few days if you don't manage to response (although you can always re-open).

**Comment by lucrib** [comment]
Thanks for the reply @jamesdbloom !
Thats works for me!
