### ISSUE TITLE
How to match a regex in the path

### ISSUE THREAD

**Issue by gauravrc** [jamesdbloom/mockserver#250]
I want to match a url like the following -

/v1/users/u-f6fsdfds878dgdfgdf7887/blogs

with a regular expression of the following form -

/v1/users/[a-zA-Z0-9-_]+/blogs

But for some reason it is not matched. I think I missing the correct syntax to make it work. Can anyone please help with this.

**Comment by lucasribeiro1990** [comment]
As far as I understood your problem is no straight related to mock-server but with a regex problem.
You can find better help here http://webchat.freenode.net/?nick=regex101-....&channels=regex

But trying to help...

The regex you have will never match the example code you gave.
In this regex you are expecting the world blogs in the end, but informing messages in the example snippet.

Try playing with it:

http://myregexp.com?regex=%2Fv1%2Fusers%2F%5Ba-zA-Z0-9-_%5D%2B%2F(blogs%7Cmessages)&text=%2Fv1%2Fusers%2Fu-f6fsdfds878dgdfgdf7887%2Fblogs%0D%0A%2Fv1%2Fusers%2Fu-f6fsdfds878dgdfgdf7887%2Fmessages%0D%0A%2Fv1%2Fusers%2Fu-azAZ0123456789-_%2Fblogs%0D%0A%2Fv1%2Fusers%2Fu-azAZ0123456789-_%2Fblogs&flags=gm

**Comment by gauravrc** [comment]
Yeah, sorry about that I fixed the note. Both have /blogs at the end.

but when I do withPath(PATH) with PATH = /v1/users/[a-zA-Z0-9-_]+/blogs, the path /v1/users/u-f6fsdfds878dgdfgdf7887/blogs is not matched for some reason.

Am I missing some escape sequences to tell mock-server to treat this expression as a regex instead of a normal string?

**Comment by masooh** [comment]
According to Javadoc `withPath` should understand regex: 
>path - the path such as "/some_mocked_path" or a regex

Regex looks fine for me, but you can try the following to identify the problem:
* `.*/v1/users/[a-zA-Z0-9-_]+/blogs.*`
* `.*v1.users.*blogs.*`
* make logging loud: `<logger name="org.mockserver" level="TRACE"/>`

**Comment by lucasribeiro1990** [comment]
Worked as expected. Look here: http://fiddle.re/gdtdra (Click on JAVA)

But if you have something before or after this string try the examples @masooh gave you (Maybe some space/new line characters hidden there).

**Comment by gauravrc** [comment]
It was happening because some other attribute was not matching. Only issue was that the attribute not matching was clearly specified in the logs which would have helped to find the issue earlier. Thanks a lot for your help.
