### ISSUE TITLE
GUI for managing (adding/deletingetc) expectations to standalone mockserver

### ISSUE THREAD

**Issue by rahulkanchi** [jamesdbloom/mockserver#275]
Atm, there isn't a GUI for adding expectation. We either have to add them programmatically via mockeserver clients (Java/Ruby/JavaScript/AJAX) or manually via curl/postman. But there isn't a common interface to manage expectations and this ticket is created to add that feature.

**Comment by sorokod** [comment]
A related functionality that would be very nice to have is a GUI for request history. The GUI would render the output of retrieveRecordedRequests() along with the "reason" as to why each failed request didn't match.

**Comment by jimkohl** [comment]
Yes this would be very helpful.  
Am working on some tools right now for my current project.
If it turns out to be useful will share it at some point.

**Comment by rajendrapenumalli** [comment]
Yes that would be the  best feature to have, please implement ASAP

**Comment by jamesdbloom** [comment]
There is now a GUI that is available on `/mockserver/dashboard` i.e. http://localhost:1080/mockserver/dashboard.  It is not yet documented and there will be considerably more work going into the GUI to extend it and improve it.  At the moment it shows the internal state in the MockServer and the log event that has been recorded.  I'm going to close this ticket because a UI exists and the documentation issue #115 covers documenting the UI.

**Comment by kreiger** [comment]
How do you use the UI to add/delete expectations?
