### ISSUE TITLE
Support RPC protoco

### ISSUE THREAD

**Issue by wangshaohua66** [jamesdbloom/mockserver#387]
For example dubbo\hessian，etc ..

**Comment by jamesdbloom** [comment]
Do dubbo\hessian use HTTP to communicate?  If so MockServer could already be used to support these types of integrations.  

Otherwise it is unlikely in the near future that MockServer would be extended to support a registry based protocol for RPC because there is an unlimited number of, such as, RMI, GPC RPC, RPyC, Distributed Ruby, etc.  Most of these are binary protocols and not HTTP based therefore most of the MockServer code would not be re-used.  If MockServer was to start supporting RPC then the code based and feature set would get to wide and too complex.  This would break the principle of single responsibility.

**Comment by 53066191** [comment]
maybe develop another mockserver support  dubbo....?
