### ISSUE TITLE
dumpLogToJava when running proxy from command line

### ISSUE THREAD

**Issue by deq9z** [jamesdbloom/mockserver#388]
Mockserver netty only generates request & response in JSON format in the log4j mockserver.log file
There is no way to change the code to use the ToJava serializer.

**Comment by jamesdbloom** [comment]
You need to a parameter to tell MockServer to dump in Java format as follows:

```
/dumpToLog?type=java
```

For more details see: https://app.swaggerhub.com/apis/jamesdbloom/mock-server-openapi/4.0.0#/expectation/put_dumpToLog

**Comment by deq9z** [comment]
I am running mock-server in proxy mode via the command line.
java -Dmockserver.logLevel=INFO -jar mockserver-netty-3.11-jar-with-dependencies.jar -proxyPort 9000 -proxyRemotePort 7001

When requesting our app via 9000, it forwards to 7001 and getting a response, however; the mockserver.log only has both request & response expectations logged in JSON format.

I tried to request /dumpToLog?type=java but as expected, it's forwarding the request to 7001 and of course, getting a response containing an error message in the content..  the request & response is logged in JSON and not in Java.

We are using JUnit for our unit and web service testing, so would like to be able to capture in Java, instead of manually converting the JSON into Java, I would rather be able to change the format than to create a Xslt stylesheet to convert JSON to Java.

**Comment by jamesdbloom** [comment]
Are you trying to call `/dumpToLog` on the proxy or MockServer.  Only the proxy currently supports printing in Java because `/dumpToLog` on the MockServer just returns the expectations that have already been submitted.

I assume from your configure of `-proxyPort 9000 -proxyRemotePort 7001` without `-proxyRemoteHost` you are using the proxy (in direct mode) to forward all requests on port 9000 on your localhost to port 7001 on your localhost.  Is that correct?  

Any forwarded requests (that the proxy has forward from port 9000 to 7001) can be dumped to the log in java format if you make a `PUT` request to `http://localhost:9000/dumpToLog?type=java`

You can also control the log file location, etc if you set the following system property in Java
```
-Dlogback.configurationFile=<fully qualified directory path>/example_logback.xml
```
replacing `<fully qualified directory path>` with the fully qualified path to the folder containing the `example_logback.xml` file.

For an example of the format see: https://github.com/jamesdbloom/mockserver/blob/0305a2fe9fabb324a1c5983d4326eee1551e7e61/mockserver-netty/src/main/resources/example_logback.xml

If you use that file you can further control the log file by using other system properties (or directly editing the file), as follows:

```
-Dlog.dir=<fully qualified directory path>
-Dmockserver.logLevel=INFO
-Droot.logLevel=TRACE
```

If you don't specify a value for `log.dir` all log files will appear in the working directory where the MockServer proxy is launch.

**Comment by jamesdbloom** [comment]
I have just implemented some changes that may benefit you.  You can now not only dumpToLog in both JSON and Java, but also retrieve requests or expectations in JSON or Java (JSON was already supported).  This are implemented in the latest SNAPSHOT version (`4.0.0-SNAPSHOT`) and will be released in the next few days once additional test coverage is added to an alternative feature for response templating.

**Comment by deq9z** [comment]
@jamesdbloom 
Correct, I am running mock proxy in direct mode by forwarding all requests from :9000 (-proxyPort 9000) to my local weblogic server on :7001 (-proxyRemotePort 7001) without -proxyRemoteHost.
I believe I have already tried doing a PUT/dumpToLog?type=java, without success.  I will try again.
I will let you know if I am able to get it logging expectations in Java.

I will also pull-in your SNAPSHOT build and will look at your code changes to understand how to log JSON and JAVA seperately.  Thanks!  Much appreciated!

**Comment by jamesdbloom** [comment]
When I have finished add test coverage I will provide some more detailed instructions and update the OpenAPI REST API specification.

**Comment by deq9z** [comment]
@jamesbloomnektan  sounds awesome!
I ran mock proxy and ran the following PUT request:
PUT http://localhost:9000/dumpToLog?type=java HTTP/1.1
Accept-Encoding: gzip,deflate
Content-Type: application/json
Content-Length: 374
Host: localhost:9000
Connection: Keep-Alive
User-Agent: Apache-HttpClient/4.1.1 (java 1.5)

{
  "headers": [
    {
      "name": "string",
      "values": [
        "string"
      ]
    }
  ],
  "cookies": [
    {
      "name": "string",
      "value": "string"
    }
  ],
  "queryStringParameters": [
    {
      "name": "type",
      "values": [
        "java"
      ]
    }
  ],
  "path": "/dumpToLog",
  "method": "PUT",
  "secure": false,
  "keepAlive": false
}

and got the following response:
HTTP/1.1 200 OK
Access-Control-Allow-Origin: *
Access-Control-Allow-Methods: CONNECT, DELETE, GET, HEAD, OPTIONS, POST, PUT, TRACE
Access-Control-Allow-Headers: Allow, Content-Encoding, Content-Length, Content-Type, ETag, Expires, Last-Modified, Location, Server, Vary
Access-Control-Expose-Headers: Allow, Content-Encoding, Content-Length, Content-Type, ETag, Expires, Last-Modified, Location, Server, Vary
Access-Control-Max-Age: 1
X-CORS: MockServer CORS support enabled by default, to disable ConfigurationProperties.enableCORSForAPI(false) or -Dmockserver.disableCORS=false
connection: keep-alive
content-length: 0

However, it is still logging expectations in JSON in both the command window and in the mockserver.log file.  Your help is much appreciated and can't wait for those instructions..

**Comment by deq9z** [comment]
@jamesbloomnektan Do you have instructions on how to dump expectations in java format?   using mock-server proxy in command line and/or using mockserverclient programmatically

**Comment by jamesdbloom** [comment]
I have just released a new major version (5.2.2) which will not include `dumpToLog`, however, instead it will be possible to use `retrieve` to retrieve:
- recorded requests in JSON
- recorded requests in Java
- active expectations in JSON
- active expectations in Java
- recorded expectations in JSON
- recorded expectations in Java
- recorded logs

The recorded expectations will include the request & response pairs recorded from the Proxy or those recorded when using a `Forward` action in MockServer (both normal `Forward` to host and port or HttpTemplate `Forward`).  This means that what you where originally trying to do will be possible AND you won't need to care / worry about where the logs are because you code will be able to retrieve the source code directly using one of the clients or the REST API.

Hopefully this should make things easier for you and anyone else who has difficulty accessing the log because, either:
- they can't easily configure the log, file location, etc
- they can't access the file system (i.e. its running in docker, the cloud, Pivotal Cloud Foundry or any other virtualised environment with limited file system access)

I will also add an extra feature to retrieve the specific match log for the a request, so that when a request doesn't match it is easier to understand why.  This means you will be able to retrieve the existing log written by MockServer (to the console) on a request by request basis.  This is the last new feature I add before I update the documentation, which will include detailed instruction on all of the above.

I will now work on updating (completely rewriting and improving) the documentation. So currently there is no documentation on this, but please use the latest Java / JavaScript clients or the refer to the OpenAPI specification https://app.swaggerhub.com/apis/jamesdbloom/mock-server-openapi/5.2.2

**Comment by deq9z** [comment]
@jamesbloomnektan  I got it going, I provided some info in issue [390](https://github.com/jamesdbloom/mockserver/issues/390)

**Comment by deq9z** [comment]
@jamesdbloom this feature is automagic!  and it makes sense implementing it this way, not only does it enforce us to use the clients programmatically and/or the REST API, but it brings consistency and ease of use, it works as a charm!  Thanks!!!!

**Comment by jamesdbloom** [comment]
great thanks, once I've updated the documentation and added support for swagger / openapi, I'll add a web UI so it'll be possible to easily see what is going on for debugging and making the proxy and MockServer much easier to use.
