### ISSUE TITLE
Enhancement dumpToLogAsJava methods in MockServerClient

### ISSUE THREAD

**Issue by deq9z** [jamesdbloom/mockserver#390]
@jamesdbloom The MockServerClient class is missing the DumpToLogAsJava method, could you implement it?  I would then be able to setup a generic forward rule and log expectations in Java, I still have not been able to get Java expectation logging yet!

**org.mockserver.client.server.MockServerClient**
- dumpToLogAsJava()
- dumpToLogAsJava(HttpRequest request)

similar to
**org.mockserver.client.proxy.ProxyClient**
- dumpToLogAsJava()
- dumpToLogAsJava(HttpRequest request)

**Comment by jamesdbloom** [comment]
I can add this, however the behaviour for MockServer is to dump the expectations that are active, i.e. those that have been setup.  So if you setup a forward expectation then called `dumpToLogAsJava(HttpRequest request)` you would only get the forward expectation you had setup (as long as it match the `HttpRequest request` parameter).

**Comment by jamesdbloom** [comment]
MockServer doesn't record responses because for all cases, except forward expectations the response is the value that has been provided in the expectation, and therefore it doesn't make sense to record it.

**Comment by deq9z** [comment]
I was suspecting this to be the case.  Can you help me dump logs in java format when running mock server in proxy mode?  Thanks!

**Comment by jamesdbloom** [comment]
You should just be able to use the `ProxyClient` and call `dumpToLogAsJava(HttpRequest request)`.

What specific issues are you having?

**Comment by deq9z** [comment]
Can you provide an example?  I tried using ProxyClient but couldn't figure out how to run it to forward and dump expectations in java format.  When you construct it you can only specify the listening port, how can I specify which port to forward request to?  Thanks!

**Comment by jamesdbloom** [comment]
in the next day or two I will release a new major version which will not include `dumpToLog`, however, instead it will be possible to use `retrieve` to retrieve:
- recorded requests in JSON
- recorded requests in Java
- active expectations in JSON
- active expectations in Java
- recorded expectations in JSON
- recorded expectations in Java

The recorded expectations will include the request & response pairs recorded from the Proxy or those recorded when using a `Forward` action (both normal `Forward` to host and port or HttpTemplate `Forward`) in MockServer.  This means that what you where originally trying to do will be possible AND you won't need to care / worry about where the logs are because you code will be able to retrieve the source code directly using one of the clients.

Hopefully this should make things easier for you and anyone else who has difficulty accessing the log because, either:
- they can't easily configure the log, file location, etc
- they can't access the file system (i.e. its running in the cloud or other virtualised environment)

I will also add an extra feature to retrieve the specific match log for the a request, so that when a request doesn't match it is easier to understand why.  This is the last new feature I add before I update the documentation, which will include detailed instruction on all of the above.

**Comment by jamesdbloom** [comment]
This has now been done and is available in the latest version 5.2.2.

I will now work on updating (completely rewriting and improving) the documentation.  So currently there is no documentation on this, but please reach out if you need some help before the documentation has been completed.
