### ISSUE TITLE
socketTimeout after 30 sec in client as server did not respond

### ISSUE THREAD

**Issue by govindndr** [jamesdbloom/mockserver#408]
i get socket timeout exception as the response not received from mock server with in 30 sec. Client is expected to throw time out exception after 30 sec.

  <95>^A21:45:32.852 [nioEventLoopGroup-3-8] DEBUG i.n.handler.logging.LoggingHandler - [id: 0x6ca86132, /host1:45335 => /host2:1080] FLUSH
^A^B    <99>^A21:46:03.806 [nioEventLoopGroup-3-12] DEBUG i.n.handler.logging.LoggingHandler - [id: 0x27540cb0, /host1:45252 :> /host2:1080] INACTIVE
A21:46:03.807 [nioEventLoopGroup-3-9] DEBUG i.n.handler.logging.LoggingHandler - [id: 0xcbaf288b, /host1:45336 :> /host2:1080] UNREGISTERED
<98>^A21:46:03.807 [nioEventLoopGroup-3-8] DEBUG i.n.handler.logging.LoggingHandler - [id: 0x6ca86132, /host1:45335 :> /host2:1080] INACTIVE

^A^B    W21:46:03.807 [nioEventLoopGroup-3-10] INFO  o.m.matchers.HttpRequestMatcher - request:

From the log file content above I could see that after 30 sec delay next request received and mockserver started processing though this request was sent from client 30 sec earlier.  Mock server configured to make a callback for matched path.

Is this threading issue? I see after all threads are unregistered next request process started. Our client sends multiple parallel requests at a time to mock server.

**Comment by jamesdbloom** [comment]
Can you provide more details:
1. What are you trying to do
1. How are you doing that
1. What client are you using
1. Can you provide the code you are using
1. Which version of MockServer are you using
1. What operating system are you using
1. Are you calling a local instance of MockServer or a remote instance of MockServer

**Comment by govindndr** [comment]
1. What are you trying to do
  I am doing automation to test our product which collects cloud resources (AWS, Azure) data for monitoring the resources. Data like cpu and memory utilization. We use real AWS account to collect data with REST Api. I use mockserver to simulate the same.

2. How are you doing that
I use mock server call back method if http request with a particular URI is received, I call back response class.

3. What client are you using
We use weblogic service in our product.

4. Can you provide the code you are using
   public void metricCallback() {        
         mockServer.when(request().withQueryStringParameter("MeasureName"))
                .callback(new HttpCallback().withCallbackClass(AwsMetricsCallBack.class.getName()));
    }

 @Override
    public HttpResponse handle(HttpRequest httpRequest) {
       public class AwsMetricsCallBack implements ExpectationCallback {

    public List<Header> setHeaders(Map<String, String> headerMap) {
        List<Header> headerValues = new ArrayList<>();
        if (headerMap != null) {
            Iterator<Map.Entry<String, String>> iterator = headerMap.entrySet().iterator();
            while (iterator.hasNext()) {
                Map.Entry<String, String> entry = iterator.next();
                Header header = Header.header(entry.getKey(), entry.getValue());
                headerValues.add(header);
            }
        }
        return headerValues;
    }
    int finalAve;
        List<Header> headerValues = setHeaders(Header());
        Logger testLog = EMTestLogger.getLogger(MethodName());
        HttpResponse httpResponse = new HttpResponse();

        int minimum = 1;
        int maximum = 100;
        Random randint = new Random();
        int randomSample = minimum + randint.nextInt((maximum - minimum) + 1);

        UUID uniqueKey = UUID.randomUUID();

        String resonseXML = "<GetMetricStatisticsResponse xmlns=" + "\"http://monitoring.amazonaws.com/doc/2009-05-15/\">"
                + "<GetMetricStatisticsResult>"
                + "   <Datapoints>"
                + "       <member>"
                + "           AVEVALUE"
                + "           <Unit>UNIT</Unit>"
                + "           <Samples>" + randomSample + "</Samples>"
                + "           <Timestamp>" + getCurrentTimestamp() + "</Timestamp>"
                + "       </member>"
                + "   </Datapoints>"
                + "   <Label>METRICNAME</Label>"
                + "</GetMetricStatisticsResult>"
                + "<ResponseMetadata>"
                + "   <RequestId>" + uniqueKey + "</RequestId>"
                + "</ResponseMetadata>"
                + "</GetMetricStatisticsResponse>";
        int minB = 1024;
        int maxB = 1060000;
        Random randAve = new Random();
        int finalAve = minB + randAve.nextInt((maxB - minB) + 1);
        String resonseXMLBytes = resonseXML.replace("AVEVALUE", "<Average>" + finalAve + "</Average><Sum>" + randomSample + "</Sum>");

        float minS = 0.0f;
        float maxS = 1.0f;
        Random randfloat = new Random();
        float finalfloat = randfloat.nextFloat() * (maxS - minS + 1.0f) + minS;
        String resonseXMLSeconds = resonseXML.replace("AVEVALUE", "<Average>" + finalfloat + "</Average><Sum>" + randomSample + "</Sum>");
        String resonseXMLCounts = resonseXML.replace("AVEVALUE", "<Average>" + randomSample + "</Average><Sum>" + randomSample + "</Sum>");

        testLog.info("Request=" + httpRequest.toString());
        List<Parameter> paramList = httpRequest.getQueryStringParameters();
        String value = null;
        for (Parameter param : paramList) {
            String name = param.getName().getValue();
            value = param.getValues().get(0).getValue();
            if (name.equals("MeasureName")) {
                testLog.info("Paramname::" + name);
                testLog.info("ParamValue::" + value);
                Boolean percent = value.contains("Usage") || value.contains("Utilization");
                Boolean bytes = value.contains("Bytes") || value.contains("In") || value.contains("Out") || value.contains("Space") || value.contains("Memory");
                Boolean Thput = value.contains("Throughput");
                Boolean iops = value.contains("IOPS");
                Boolean latency = value.contains("Latency") || value.contains("Replica");
                if (percent) {

                    httpResponse.withStatusCode(200).withHeaders(headerValues)
                            .withBody(resonseXMLCounts.replace("UNIT", "Percent").replace("METRICNAME", value));
                } else if (bytes) {

                    httpResponse.withStatusCode(200).withHeaders(headerValues)
                            .withBody(resonseXMLBytes.replace("UNIT", "Bytes").replace("METRICNAME", value));
                } else if (Thput) {

                    httpResponse.withStatusCode(200).withHeaders(headerValues)
                            .withBody(resonseXMLBytes.replace("UNIT", "Bytes/Second").replace("METRICNAME", value));
                } else if (iops) {

                    httpResponse.withStatusCode(200).withHeaders(headerValues)
                            .withBody(resonseXMLCounts.replace("UNIT", "Count/Second").replace("METRICNAME", value));
                } else if (latency) {
                    httpResponse.withStatusCode(200).withHeaders(headerValues)
                            .withBody(resonseXMLSeconds.replace("UNIT", "Second").replace("METRICNAME", value));
                } else {

                    httpResponse.withStatusCode(200).withHeaders(headerValues)
                            .withBody(resonseXMLCounts.replace("UNIT", "Count").replace("METRICNAME", value));
                }
            }

        }
        testLog.info("Response=" + httpResponse.toString());
        return httpResponse;

    }

5. Which version of MockServer are you using
mockserver-netty:3.10.2

6. What operating system are you using
Linux 

7.Are you calling a local instance of MockServer or a remote instance of MockServer
Remote instance 


Will below solution work for my issue? 

mockServerClient
        .when(
                request()
                        .withPath(calculatePath("some_path1"))
        )
        .respond(
                response()
                        .withBody("some_body1")
                        .withDelay(new Delay(TimeUnit.MILLISECONDS, 10))
        );

This one is available here https://github.com/jamesdbloom/mockserver/issues/235

**Comment by govindndr** [comment]
can you please advice? Is this issue in mock server threads? How to proceed further? Can we resolve this issue?

**Comment by govindndr** [comment]
Will running mock server deploying war in tomcat solve this issue?

**Comment by jamesdbloom** [comment]
I suspect that you client is not able to make calls to the MockServer because of one of the following reasons:
1. client is not configured with the correct ip and port number of the remote instance
1. network doesn't allow a connection from when the code above is running to where the MockServer is running, i.e. firewall problem / subnet problem / VM or container not exposing port
1. MockServer is not running at the time that the test runs

Can you please test this hypothesis and provide any information you have.

Basically the error you are getting is that MockServer client can not talk to MockServer.  It is extremely unlikely to be anything to do with Threads because I regularly run load tests against MockServer hitting it with 100 simultaneous clients in a continuous loop for 5 minutes.  It handles this without any issue with a p95 of 200 ms and a p50 of < .1 ms.

It also looks like you are running a slightly old version of MockServer.  Although this should have nothing to do with your issue it may be worth upgrading at some point.

**Comment by govindndr** [comment]
1. client is not configured with the correct ip and port number of the remote instance
This can't be the issue as failure happens only for few requests and that too when many requests (> 100) submitted at a time.

2. network doesn't allow a connection from when the code above is running to where the MockServer is running, i.e. firewall problem / subnet problem / VM or container not exposing port

We have verified all infrastructure issues. No issue observed during this time.

MockServer is not running at the time that the test runs

This can't be the case as I stop the mock server after I get all responses having wait time of  30mins in code.

Note: As of now I dont face this issue as I reduced load on mock server.

**Comment by jamesdbloom** [comment]
Your issue could potentially be due to a performance problem in 5.3.0 if you callback method was very slow to execute because it is holding a thread from the limited thread pool while it executes. 

I have fixed this issue and callback methods are executed in a non-blocking manner.  I have also made numerous other performance improvements (in some areas increasing performance by 80x), the performance statistics are shown below.

It'll be a a few weeks before the new change are released, however if you want to take advantage of the performance improvements straight away you can use the [snapshot maven dependency](http://mock-server.com/where/maven_central.html#sonatype_snapshot) or the [mockserver-snapshot docker tag](https://hub.docker.com/r/jamesdbloom/mockserver/tags/).

The current statistics where recorded by testing on an EC2 medium instance in AWS with both the performance test tool [locust](https://locust.io/) and the MockServer running on the same VM in separate docker containers.  That is not idea conditions for a performance test but adequate and multiple test runs showed similar results.

**--> SCROLL RIGHT ON TABLE TO SEE FULL RESULTS**

 req/s|#threads|#reqs|  #fails|Avg|Min| Max|Median|50%|66%| 75%| 80%| 90%| 95%| 98%| 99%|100%
:-----|:-------|:----|:-------|:--|:--|:---|:-----|:--|:--|:---|:---|:---|:---|:---|:---|:---
 10.00|      10|  609|0(0.00%)|  3|  2|  12|     3|  3|  3|   3|   3|   4|   4|   6|   7|12
 99.70|     100| 6099|0(0.00%)|  2|  1|  15|     2|  2|  2|   2|   2|   3|   4|   5|   6|15
199.30|     200|12199|0(0.00%)|  2|  1|  20|     2|  2|  2|   2|   3|   3|   4|   6|   7|20
297.80|     300|18299|0(0.00%)|  2|  1|  31|     3|  3|  3|   3|   4|   4|   5|   7|   9|31
397.30|     400|24399|0(0.00%)|  4|  1|  52|     4|  4|  5|   6|   6|   8|  10|  16|  21|52
493.30|     500|30499|0(0.00%)|  7|  1|  70|     6|  6|  7|   9|  10|  15|  22|  30|  37|70
571.90|     600|36599|0(0.00%)| 17|  1| 159|    10| 10| 15|  21|  25|  42|  65|  90| 110|159
656.30|     700|42699|0(0.00%)| 34|  1| 202|    25| 25| 42|  53|  60|  78|  93| 110| 120|202
663.70|     800|48799|0(0.00%)|184|  2| 528|   190|190|250| 280| 300| 350| 390| 420| 440|528
733.80|     900|54899|0(0.00%)|182|  4| 402|   190|190|220| 240| 250| 270| 290| 320| 340|402
704.20|    1100|67099|0(0.00%)|392|  4| 740|   390|390|440| 470| 490| 550| 600| 640| 660|740
705.90|    1200|73199|0(0.00%)|495|  4|1002|   490|490|600| 670| 700| 770| 820| 870| 900|1002
691.00|    1300|79299|0(0.00%)|650| 12|1280|   710|710|830| 900| 940|1000|1100|1100|1100|1280
676.90|    1400|85399|0(0.00%)|741| 13|1292|   750|750|840| 890| 930|1000|1100|1100|1200|1292
694.60|    1500|91499|0(0.00%)|886|107|1597|   890|890|990|1000|1100|1200|1200|1300|1400|1597 

I'm going to close this issue as I believe this was fixed in: #403
