### ISSUE TITLE
Chained Proxy for Mockserver

### ISSUE THREAD

**Issue by anonfriese** [jamesdbloom/mockserver#416]
Hi there,

I'd like to use Mockserver in a project and have problems configuring a chained/upstream/parent Proxy.
Unfortunately I'm only able to access Servers on the internet via proxy server.

So I need to get the following Chain to work:

HTTP-Client --> Mockserver --> HTTP-Proxy(SQUID) --> Webservice

I already configured my HTTP Client to use the Mockserver Proxy-Port. This seems to work fine.

Unfortunately Mockserver can't access the Webservice directly because our Firewalls drops this traffic. So Mockserver needs to use an HTTP-Proxy and make a HTTP CONNECT there (the Webservice is encrypted). Unfortunately I'm not able to configure that and haven't found anything in the documentation. Is there an Option to configure Mockserver to use a Proxy for connecting further?

**Comment by jamesdbloom** [comment]
There is currently no support for proxying MockServer outbound connections in a generic way, although this could be added, if required.

As an alternative you should be able to use the direct proxy by setting the `proxyRemotePort` and `proxyRemoteHost`.  This would allow you to directly connect to any endpoint acting as a reverse proxy that just sends all requests to the `proxyRemotePort` and `proxyRemoteHost`.  However if your client still makes an HTTP CONNECT I think this will be picked up by MockServer as an HTTP CONNECT request to its self (instead of your SQUID proxy).  It should be fairly easy to fix that issue by disabling support for HTTP CONNECT and SOCKS when in direct proxy mode, because there is no reason to intercept HTTP CONNECT or SOCKS messages when in direct proxy mode.

Currently I'm in the middle of some work on performance enhancements and some changes to the API to extend proxying support (allowing modification of requests being proxied).  

However, I could make the modifications you need (to disable HTTP CONNECT and SOCKS support in direct proxy mode) if your happy using the SNAPSHOT version.  There is nothing wrong with the SNAPSHOT version except that limited number of API changes haven't been documented.  I should be able to finish that in the next 5 days or so.  I don't want to do a new release yet until I complete some other work to introduce a UI that will show the request passing through the MockServer in real time and other internal data (logs, active expectations, etc).

Does that all make sense?

**Comment by anonfriese** [comment]
Hi James,

If I understand correctly, this would mean I configure the proxyRemoteHost/Port to my corporate proxy and mockserver would then forward all requests. If I do that currently, I get the following Message:

```
Caused by: io.netty.handler.ssl.NotSslRecordException: not an SSL/TLS record: 48.........
	at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1137) ~[netty-handler-4.1.17.Final.jar:4.1.17.Final]
	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1193) ~[netty-handler-4.1.17.Final.jar:4.1.17.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:489) ~[netty-codec-4.1.17.Final.jar:4.1.17.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:428) ~[netty-codec-4.1.17.Final.jar:4.1.17.Final]
	... 20 more 
```

However if I understand correctly, this would also mean that Mockserver would just pass the connection. I explicitly want to intercept the HTTP CONNECT's from Mockserver and decrypt the encrypted Traffic, Right now I think Mockserver connects to our Proxy in SSL-Mode and tries to talk encrypted to our HTTP Port. This wouldn't be of much use to me.

I think what Mockserver needs to do is intercept the HTTP CONNECT like it would normally do if used in proxy Mode, then intercept the HTTPS-Connection and then make it's own HTTP Connect to our Upstream Proxy.

I hope that makes sense as well :-)

**Comment by jamesdbloom** [comment]
Yes I agree, I think I may have a solution that would allow the onward connection to be proxied via another HTTP CONNECT or SOCKS proxy.  I've tested it manually but haven't written any integration / unit tests.  Once I do that I can commit.  The basic approach would require you to set either of the following two system properties `mockserver.httpProxy` or `mockserver.httpSocksProxy` providing a <host>:<port> format as follows:

```bash
-Dmockserver.httpProxy=127.0.0.1:1081
```

**Comment by jamesdbloom** [comment]
I have completed implementing this logic and have finished the integration tests.  I will make a new release in a few weeks, but in the meantime you can use the SNAPSHOT version available both for [maven](http://mock-server.com/where/maven_central.html#sonatype_snapshot) or [docker](https://hub.docker.com/r/jamesdbloom/mockserver/tags/)
