### ISSUE TITLE
Unable to mock https request for Apache HttpClient

### ISSUE THREAD

**Issue by masher82** [jamesdbloom/mockserver#418]
I am trying to mock an external https call that is executed via Apaches HttpClient. The mock server is defined via "http.proxyHost" and "https.proxyHost" environment variables.

Initially I tried to use the desired method type for the mocked request but this result in ...
```
2018-01-17T10:14:42,762+0100 INFO  [nioEventLoopGroup-3-1] org.mockserver.logging.LogFormatter.infoLog(LogFormatter.java:34)
creating expectation:{  "httpRequest" : {    "method" : "GET",    "path" : "/languages"  },  "times" : {    "remainingTimes" : 0,    "unlimited" : true  },  "timeToLive" : {    "unlimited" : true  },  "httpResponse" : {    "statusCode" : 200,    "body" : {      "type" : "BINARY",      "base64Bytes" : "W3sibGFuZ3VhZ2VfaWQiOiAxLCJuYW1lIjogIkRldXRzY2giLCJpc29fNjM5XzEiOiAiZGUifSx7Imxhbmd1YWdlX2lkIjogMiwibmFtZSI6ICJFbmdsaXNoIiwiaXNvXzYzOV8xIjogImVuIn1d"    }  },  "action" : {    "statusCode" : 200,    "body" : {      "type" : "BINARY",      "base64Bytes" : "W3sibGFuZ3VhZ2VfaWQiOiAxLCJuYW1lIjogIkRldXRzY2giLCJpc29fNjM5XzEiOiAiZGUifSx7Imxhbmd1YWdlX2lkIjogMiwibmFtZSI6ICJFbmdsaXNoIiwiaXNvXzYzOV8xIjogImVuIn1d"    }  }}

2018-01-17T10:14:50,893+0100 INFO  [nioEventLoopGroup-3-2] org.mockserver.logging.LogFormatter.infoLog(LogFormatter.java:34)
request:{  "method" : "CONNECT",  "path" : "api.mydesiredendhost.com:443",  "headers" : [ {    "name" : "Host",    "values" : [ "api.mydesiredendhost.com" ]  }, {    "name" : "User-Agent",    "values" : [ "The user agent" ]  }, {    "name" : "content-length",    "values" : [ "0" ]  } ],  "keepAlive" : true,  "secure" : false}
 did not match expectation:{  "method" : "GET",  "path" : "/languages"}
 because:method matches = falsepath matches = falsequery string parameters match = truebody matches = trueheaders match = truecookies match = truekeep-alive matches = truessl matches = true
```

... so I removed the explicit method definition and now the result is ....

```
2018-01-17T13:33:46,465+0100 INFO  [nioEventLoopGroup-3-2] org.mockserver.logging.LogFormatter.infoLog(LogFormatter.java:34)
request:{  "method" : "CONNECT",  "path" : "api.mydesiredendhost.com:443",  "headers" : [ {    "name" : "Host",    "values" : [ "api.mydesiredendhost.com" ]  }, {    "name" : "User-Agent",    "values" : [ "The user agent" ]  }, {    "name" : "content-length",    "values" : [ "0" ]  } ],  "keepAlive" : true,  "secure" : false}
 did not match expectation:{  "path" : "/languages"}
 because:method matches = truepath matches = falsequery string parameters match = truebody matches = trueheaders match = truecookies match = truekeep-alive matches = truessl matches = true
```
... so the host is mixed up into the path parameter. 

From the Apache documentation: ```Tunneled HTTPS connections through HTTP proxies, via the CONNECT method.```

Is there something I misunderstood; am I doing something wrong or is there an issue with Apaches HttpClient and if so, what might be a possible workaround?

Just want to mention: Having the same call with http scheme works as expected.

**Comment by jamesdbloom** [comment]
In the current version of MockServer mocking and proxying are two completely separate concepts.

Therefore when you setup a mock this has no impact on the proxy behaviour.  

You have configured ApacheHttpClient to use MockServer as a proxy and therefore the mocks don't get triggered.

In addition the request you are seeing in the logs is an HTTP CONNECT request that ApacheHttpClient sends initially to the proxy to setup a tunnel.  Once this tunnel is setup all subsequent requests pass through this tunnel.  The format of the HTTP CONNECT request is such that the remote host and port of the tunnel appears in the path section of a generic HTTP request.

So I would suggest two things:
1. please include your code so that I can ensure I have fully understood your use case and can confirm my hypothesis
2. switch to use the latest SNAPSHOT version of MockServer in which the mocking and proxying logic has effective been combined into a single solution, this enabled the mocking of proxied requests and configuring a mock by only configuring a proxy, for details on how to use the SNAPSHOT version please see: http://mock-server.com/where/maven_central.html#sonatype_snapshot

**Comment by masher82** [comment]
Just want to give one additional information that might be missing: I am not able to target the client requests only to 'localhost' resources as they are not configurable and have an explicit endpoint.

**Comment by jamesdbloom** [comment]
With the latest [SNAPSHOT](http://mock-server.com/where/maven_central.html#sonatype_snapshot) version (not yet released) you can use the proxy to mock request/responses.  This way if you configure the proxy in ApacheHttpClient then you can catch all outbound requests. The request from ApacheHttpClient that match an expectation will be mocked, those that don't the proxy will act as a normal proxy (i.e. for the request on) but you can verify all requests those that match an expectation and those that don't.

To using mocking in the currently released version of MockServer you need to update the location that the ApacheHttpClient is sending a request to.  For example if you client is sending a search query to `www.google.com` you would change that to send to the MockServer i.e. `localhost:1080` and you would mock the response from google.  

I'm going to close this issue as I don't think there is a bug, but please re-open or open a new issue if you have a bug.
