### ISSUE TITLE
Cannot set log level through maven plugin POM configuration

### ISSUE THREAD

**Issue by gdabski** [jamesdbloom/mockserver#430]
In latest version (5.3.0) Mock Server appears not to respect the log level defined in the <logLevel> configuration element in a project's POM file and sends all INFO logs to standard output regardless of configuration. Documentation specifies WARN as being the default threshold.

**Comment by jamesdbloom** [comment]
This is already fixed and will be available in the next release.  However, I'll leave this issue open until there is at least a SNAPSHOT version with the fix.

FYI - the way MockServer does logging and handles the log level has been completely refactored due to limitations with the way all logging frameworks (Logback, Log4j, Log4j2, JCL, JUL) store logging context statically making it effectively impossible to effectively handling logging level in numerous scenarios (such as plugin or in project with another log configuration file, etc) when using SLF4J.  SLF4J does expose control to change log levels.

**Comment by jamesdbloom** [comment]
This is now fixed and available in the latest SNAPSHOT version.  I will release this in the next few weeks.

**Comment by gdabski** [comment]
Thank you very much for your reaction and support.
