### ISSUE TITLE
Support for optional request headers

### ISSUE THREAD

**Issue by shahamit** [jamesdbloom/mockserver#444]
I couldn't find a way to specify a request header to be optional. Is there any way to do so? An example would be good in case the support is already present.

**Comment by jamesdbloom** [comment]
MockServer ignores additional headers.  So one way to specify an optional header is to have to setup two expectations. The first expectation contains the optional header so that it is attempted to be matched first.  The second expectation contains a negative matcher forcing the optional header not to be present.  That way either the first expectation will be attempted to be matched is a request has the header or the second will attempted to be matted if the request doesn't have the header.

Perhaps you could explain more about the use case you are trying to implement so that I can understand if your requirements are already met or if a new feature is needed.
