### ISSUE TITLE
Stopping Mockserver-Container takes about 10 seconds

### ISSUE THREAD

**Issue by jehof** [jamesdbloom/mockserver#493]
It seems that the Mockserver-Container does not handle the docker stop command properly so that it will be killed (forced) after the default timeout of 10 seconds.

> 2018-06-20T11:22:40.307436600+02:00 container start c72ad60586f0cfdb1f471bc749634a8ab198bb7ecc43def8d1bfa09bb38df80a (image=jamesdbloom/mockserver, name=gallant_bhaskara)

> 2018-06-20T11:23:01.652187200+02:00 container kill c72ad60586f0cfdb1f471bc749634a8ab198bb7ecc43def8d1bfa09bb38df80a (image=jamesdbloom/mockserver, name=gallant_bhaskara, signal=15)

> 2018-06-20T11:23:11.668604500+02:00 container kill c72ad60586f0cfdb1f471bc749634a8ab198bb7ecc43def8d1bfa09bb38df80a (image=jamesdbloom/mockserver, name=gallant_bhaskara, signal=9)

> 2018-06-20T11:23:11.818113800+02:00 container die c72ad60586f0cfdb1f471bc749634a8ab198bb7ecc43def8d1bfa09bb38df80a (exitCode=137, image=jamesdbloom/mockserver, name=gallant_bhaskara)

> 2018-06-20T11:23:12.340376000+02:00 network disconnect cc2c936f4a1ecf92d0058fd2110901b94a9c1a72355689df1e81df4733a2a524 (container=c72ad60586f0cfdb1f471bc749634a8ab198bb7ecc43def8d1bfa09bb38df80a, name=bridge, type=bridge)

> 2018-06-20T11:23:12.443712000+02:00 container stop c72ad60586f0cfdb1f471bc749634a8ab198bb7ecc43def8d1bfa09bb38df80a (image=jamesdbloom/mockserver, name=gallant_bhaskara)

**Comment by rmetcalf9** [comment]
I have seen this before in my Docker containers. It happens when the Docker container runs a script and that script kicks off another process. The Term/Kill signals are received by the bash script but not sent on to the Java process which keeps running. Docker then has a timeout while it is waiting for the process to stop but it will never stop becasue it never got the stop signal!

It is explained better than I can here:
https://veithen.github.io/2014/11/16/sigterm-propagation.html

I fixed it in my own containers by adding code to the bash script which propergated the term signals to my sub processes. I think the same fix will work here.

**Comment by jamesdbloom** [comment]
this is now fixed and will be in the next release of the `latest` tag (once the build completes)
