### ISSUE TITLE
How to add a certificate ?

### ISSUE THREAD

**Issue by albabosh** [jamesdbloom/mockserver#504]
I use mockserver as a reverse proxy server. Is it possible to add a valid ssl cert to mockserver (as I do for nginx or apache) ? I need it because the client will only connect to a server with a valid cert.

**Comment by jamesdbloom** [comment]
Can you please provide more details about what you mean when you say a valid certificate.

MockServer currently auto generates valid certificates as long as it has the information required to generate the certificate.  To do this it needs to know the host name of the service it is mocking.  If an expectation is setup including the `Host` header then this is the easiest way to achieve this.  In addition it is important to ensure your client trusts the MockServer CA cert.  There is an example script showing how to add the MockServer CA cert into the JVM: https://github.com/jamesdbloom/mockserver/blob/master/scripts/install_ca_certificate.sh otherwise there are site that explain how to add a CA cert into windows or other OSes, such as: http://www.sqlservermart.com/HowTo/Windows_Import_Certificate.aspx

**Comment by udev** [comment]
Is there any documentation on www.mock-server.com regarding how to set certificates up? I ran into the same issue(s) as @albabosh and wasn't aware of the install_ca_certificate.sh script until discovering this issue. I ultimately ended up downloading the pem file directly from https://raw.githubusercontent.com/jamesdbloom/mockserver/master/mockserver-core/src/main/resources/org/mockserver/socket/CertificateAuthorityCertificate.pem and double clicked it to add it to the OSX keystore manually. Hardly ideal.
