### ISSUE TITLE
Possibility to configure the interfaces the server is listening on

### ISSUE THREAD

**Issue by Vampire** [jamesdbloom/mockserver#520]
I'd like to have the possibility to configure on which interfaces the server is listening on.
As far as I have seen, currently it is always listening on IP `0`.
But e. g. for running tests I'd like to have the server only listening on the loopback interface.
There is no need to listen on external interfaces in this case.
Actually I'd even suggest to only listen on the loopback interface by default, providing the possibility to configure an arbitrary amount of interfaces to listen on like other software also does by default.

**Comment by jamesdbloom** [comment]
I agree making this configurable is a good idea.  However, if the MockServer was changed to only listen on the loopback interface that would be a breaking change that could confuse some users.  The reason it listening on `0.0.0.0` is because there are numerous ways the SUT can refer to the local machine and it isn't always using the loopback.  Some users are not aware of these low level details and have previously raised bugs on MockServer due to issues like this.  So making MockServer just work by default for as many people as possible is important.  Adding configuration to override this though is a good idea for those, like you, who want something more specific and understand the details.

**Comment by jamesdbloom** [comment]
added new configuration property so you can specify the local bound IP.
