### ISSUE TITLE
Java .withDelay() not working as expected.

### ISSUE THREAD

**Issue by BharathM** [jamesdbloom/mockserver#526]
I have used the following function to delay the response but the system doesn't wait. 
.withDelay(TimeUnit.MINUTES, 10);

**Comment by BharathM** [comment]
I have used following code to overcome above issue

TimeUnit.SECONDS.sleep(SleepTime);

**Comment by jamesdbloom** [comment]
The withDelay field sets a delay for the response to be sent from the server when an expectation is matched.  This is not introduce any delay at the time of creation an expectation.  I suspect given the code you have shown resolves your issue you need a delay after setting up an expectation.  MockServer is not designed to do this and if you need this I suggest you use the code you provided.  I'm going to close this ticket because I don't believe it is an issue but please re-open it if you feel I have mis-understood your issue.
