### ISSUE TITLE
Proxy callback can't mock or forward the request

### ISSUE THREAD

**Issue by danielberrutti** [jamesdbloom/mockserver#535]
Hi, first of all congratulations for such a great work.
I'm new to mockserver, -so this is certainly not a proper issue, just lack of knowledge- this is what I'm trying to do:
I set up a selenium proxy redirecting all calls from the browser to localhost:8080
Then I set a MockServerClient, and what I need to do is that https requests to some url must obtain a static response, while others need to be forwarded
I tried this:
MockServerClient mockServerClient = new MockServerClient("localhost", 8080);
	    mockServerClient
	    .when(
	        request()
	            .withPath("/some_path_I_need_to_intercept")
	            .withMethod("POST")
	    )
	    .respond(new HttpResponse().withBody("some whatever body"));
                    
	    mockServerClient
	    .when(
	        request()
	            .withPath("/*")
	    )
	    .forward(
	        forward()
	            .withHost("host.host.com")
	            .withPort(443)
	            .withScheme(HttpForward.Scheme.HTTPS)
	    );
But didn't work, no responses at all.
then I tried to use a ExpectationCallback action, but I couldn't find a way to forward the request when it doesn't need to be mocked and return the response from host.
Is there a way to achieve this?

Thank you very much in advance.

**Comment by jamesdbloom** [comment]
Can you provide more code so I can understand the order you are adding your expectations.  At face value what you describe sounds correct and should work.  However, if you are adding the forward expectation first then this will always be matched.  You need to create the most specific expectations first and then less specific expectations last.  In addition it is a good idea to make expectation as specific as you can (without making things complex) so that it is easy to ensure one expectation doesn't match a request you're note expecting.

**Comment by jamesdbloom** [comment]
Please provide re-open issue when requested information is provided
