### ISSUE TITLE
Document MockServer UI

### ISSUE THREAD

**Issue by jamesdbloom** [jamesdbloom/mockserver#574]
Document MockServer UI

**Comment by jamesdbloom** [comment]
closing as covered by #115

**Comment by alshari86** [comment]
Hi @jamesdbloom 
I am still not clear about:
if I run the mockserver stand alone via command:
java -jar /Users/linai/Documents/mockserver/mockserver-netty-5.5.1-jar-with-dependencies.jar -serverPort 5000 -logLevel INFO
Then how do I setup the json file with request and response expectation?
It mentioned initialization class here: 
http://www.mock-server.com/mock_server/initializing_expectations.html
But how do i access the class and create expectation so that when I run the command, it will pickup response in each expectation?
