### ISSUE TITLE
Unable to override default logging in Docker

### ISSUE THREAD

**Issue by georgewilk01** [jamesdbloom/mockserver#609]
I am attempting to debug an issue with JAVASCRIPT template expectation and having problems overriding default logging level when running MockServer in the docker container.  Here is my command line:

`docker run --name mockserver -d -p 1080:1080 jamesdbloom/mockserver /opt/mockserver/run_mockserver.sh -serverPort 1080 -logLevel TRACE`

I shelled into the running container and the java process cmd looks as follows:

`java -Dfile.encoding=UTF-8 -jar /opt/mockserver/mockserver-netty-jar-with-dependencies.jar -serverPort 1080 -logLevel DEBUG`

I am tailing the logs as follows:

`docker logs -f mockserver`

All I get is high-level INFO logging. What am I missing?

**Comment by Jorge-Moreira** [comment]
The `run_mockserver.sh` don't use the environment variable. It can be because of that...

**Comment by jamesdbloom** [comment]
To update set the logging please use the following command:

```bash
docker run --rm --name mockserver -p 1080:1080 jamesdbloom/mockserver -serverPort 1080 -logLevel TRACE
```

Because the Dockerfile has an entrypoint the arguments specified after the `jamesdbloom/mockserver` are parsed by docker to the `/opt/mockserver/run_mockserver.sh` script, which is the entrypoint.

For full details please see the documentation: http://mock-server.com/mock_server/running_mock_server.html#docker_container_customization
