### ISSUE TITLE
initializationJsonPath not work how maven propertie

### ISSUE THREAD

**Issue by edjo192000** [jamesdbloom/mockserver#640]
Hi.

I'm trying to use _initializerJson.json_ for setup expectations, I'm use maven for this, but not work it, my _pom_ is the next
```
  <properties>
 <mockserver.initializationJsonPath>${project.basedir}/src/test/resources/initializerJson.json</mockserver.initializationJsonPath>

  </properties>
.
.
.
      <plugin>
        <groupId>org.mock-server</groupId>
        <artifactId>mockserver-maven-plugin</artifactId>
        <version>5.5.4</version>
        <configuration>
          <serverPort>1180</serverPort>
          <logLevel>DEBUG</logLevel>
        </configuration>
        <executions>
          <execution>
            <id>process-test-classes</id>
            <phase>process-test-classes</phase>
            <goals>
              <goal>start</goal>
            </goals>
          </execution>
          <execution>
            <id>verify</id>
            <phase>verify</phase>
            <goals>
              <goal>stop</goal>
            </goals>
          </execution>
        </executions>
      </plugin>

```

Can you help me so that the expectations are configured with the json file?
Thanks for the help.

**Comment by jamesdbloom** [comment]
The `mockserver.initializationJsonPath` value needs to be set as a Java System Property.  Doing this with maven is effectively impossible due to the over complex way maven forks plugins and tries to unnecessarily segregate everything.  I tried to expose an additional maven property however due to the over complex way the classpath is segregated in maven plugins this seems to be very complex and normal techniques to load content form the classpath don't work.

I will try again to expose this functionality despite maven making it effectively impossible and over complex.

Unfortunately I've come to realise over the years that both maven and gradle are massively over complex and over engineered and seem to be an exercise in their authors building the most complex way possible to perform java builds.  This is particularly clear when compared to builds systems from every other language.  The impact being that plugins are much much harder to build and keep working reliably than they should / could be.

**Comment by jamesdbloom** [comment]
This is now committed to the plugin repo and will be release in the next few days once I have updated the documentation.

An example of how to use this new property is as follows:

```xml
<plugin>
    <groupId>org.mock-server</groupId>
    <artifactId>mockserver-maven-plugin</artifactId>
    <version>5.5.5-SNAPSHOT</version>
    <configuration>
        <logLevel>DEBUG</logLevel>
        <pipeLogToConsole>true</pipeLogToConsole>
        <serverPort>1080,2080</serverPort>
        <initializationJson>org/mockserver/initializerJson.json</initializationJson>
        <pipeLogToConsole>false</pipeLogToConsole>
    </configuration>
    <executions>
        <execution>
            <id>process-test-classes</id>
            <phase>process-test-classes</phase>
            <goals>
                <goal>start</goal>
            </goals>
        </execution>
        <execution>
            <id>pre-integration-test</id>
            <phase>pre-integration-test</phase>
            <goals>
                <goal>stop</goal>
            </goals>
        </execution>
    </executions>
</plugin>
```
