### ISSUE TITLE
Unable to use javascript template response require packages

### ISSUE THREAD

**Issue by sbakhi** [jamesdbloom/mockserver#650]
Having modified the Dockerfile to install nodejs and nodejs-npm, I am unable to use node packages and modules in a javascript template response. The template works just file if its pure javascript but fails to return once require keyword is used. 

Any ideas on how to accomplish this if at all possible?

**Comment by jamesdbloom** [comment]
There is no support for nodejs in the templated responses, only pure javascript because the template executes inside the JVM.  I'm not sure if / how such support could ever be added.  If you need this type of behaviour I would suggest using the callbacks instead. http://mock-server.com/mock_server/creating_expectations.html#button_forward_method_or_closure_callback
