### ISSUE TITLE
Support for URL (percent) encoding?

### ISSUE THREAD

**Issue by wujek-srujek** [jamesdbloom/mockserver#666]
Hi, we are using MockServer 5.4.1 and Spring Boot 2.1.7.RELEASE with WebFlux and the new WebClient. By default, the client URL encodes certain characters, like @ or +. The expectations seem not to support that, i.e they require us to explicitly put the encoded:

    mockServerRule.getClient()
        .when(
            request()
                .withMethod("GET")
                .withPath("/users/ab%40c.de") // would like to put ab@c.de
        )
        .respond()
        ....

Is there an API for this use case, will there be, or am I doing things wrong?

**Comment by jamesdbloom** [comment]
If you need to URL encode the path automatically I would suggest you use the `java.net.URLEncoder.encode(String s, String enc)` that is part of the JDK.  It would not be possible for MockServer to automatically URL encode values because the path matcher supports regular expressions.  Automatic URL encoding would break the regular expressions.

Just use the following code to achieve what you need:

```javascript
mockServerClient
    .when(
        request()
            .withMethod("GET") 
            .withPath(URLEncoder.encode("/users/ab@c.de", StandardCharsets.UTF_8.name()))
    )
    .respond(
        response()
            .withBody("some_body_response")
    );
```
