### ISSUE TITLE
Verification limitations

### ISSUE THREAD

**Issue by OsvaldasRubavicius** [jamesdbloom/mockserver#678]
Hello, I've wanted to use mockserver for load-testing scenarios but it seems that I've hit some limits - e.g. I hit a configured expectation method 1000 times. When I use verify endpoint it returns 202 response only when I supply "atLeast" parameter less than ~600. I've also tried to use "/mockserver/retrieve?type=REQUESTS" url given the same configured matcher, but the maximum amount of results returned was only 666. I've found no documentation around any limitations, so not sure if this is an actual issue or I'm hitting some other technical limits.

For me it would be really helpful to have a simple way to get a number of how many times configured endpoint was called.

**Comment by jamesdbloom** [comment]
I think your issue is related to #656 which is now fixed.  I will make a new release in the next few weeks with this fix.  In the meantime, you could try using the SNAPSHOT version at http://mock-server.com/where/maven_central.html#sonatype_snapshot or https://hub.docker.com/layers/jamesdbloom/mockserver/mockserver-snapshot/images/sha256-7ae867cc1e137e1100629deeac04305c360fa66804448f4f78e506b8d1e0326e
