### ISSUE TITLE
C# Client and GitHub Org

### ISSUE THREAD

**Issue by say25** [jamesdbloom/mockserver#686]
@jamesdbloom we wrote a lightweight C# client. I would love to put it in a place where others can use it. 

1. Is it possible to create a GitHub org that I can transfer ownership of the code to?
1. I would think having a GitHub org to host all the MockServer related code may help?

**Comment by jamesdbloom** [comment]
Yes, I agree I did create a github org but I haven't yet transferred all the code there.  I am happy to do this.

It would also be good to have a C# client.  I've done some C# but I haven't shared libraries in C#. Where do you publish your client, what is the equivalent of maven for C#?

**Comment by say25** [comment]
NuGet is the equivalent of maven for .Net (C# and F#) can consume it. I was hoping to just publish it directly to a GitHub org. I will need to clean up some of the specific to our use case stuff as well before making it truly public.

**Comment by jamesdbloom** [comment]
That sounds good, I'm happy to publish it myself to NuGet once a CD pipeline etc has been setup.

**Comment by jamesdbloom** [comment]
on reflection, I'll create a new C# client from scratch because I want the code to be as close as possible to the existing Java client.  This is because there is / will be clients in Java, JavaScript, C#, Python and Ruby.  Unless they are all as close as possible to each other code-wise it'll be much more expensive to add new features.  Keep them as aligned as possible will reduce the cost of making changes 5 times.

**Comment by jamesdbloom** [comment]
new feature requests now prioritised on Trello, so closing issue in GitHub, only bugs or unaccepted feature requests will stay in GitHub, so that new feature backlog can be more effectively managed, see: https://trello.com/c/EfkxkzGy/36-create-c-client and https://trello.com/c/gxaCDqXr/38-move-to-mock-server-github-organisation
