### ISSUE TITLE
Dashboard goes empty when req/s is more than ~5

### ISSUE THREAD

**Issue by ilamparithiNatarajan** [jamesdbloom/mockserver#690]
Hi @jamesbloomnektan ,

I was trying Locust to load test our expectations, when I increase RPS to 5, mockserver/dashboard doesn't get updated. And if I refresh, it goes empty. Any idea about this ?

PS. Thank you so much for your work !!

**Comment by jamesdbloom** [comment]
I'll take a look

**Comment by jamesdbloom** [comment]
I made a number of improvements that have made the UI much more responsive under heavy load. I've tested it under 5 req/s for 5 minutes and it consistently works.  There are however more significant changes that could be made to support much greater scalability, but the majority of those are pretty major refactorings.

**Comment by ilamparithiNatarajan** [comment]
Fab! Thanks a lot for having a look and the improvements.

**Comment by jamesdbloom** [comment]
There are some more improvements I'll make, I just need to test if the improvements I have in mind will work with react / redux.  Once I've done that and added more automated testing of the UI I'll add documentation on the website.

**Comment by jamesdbloom** [comment]
I've made further improvements so that the dashboard works reliably up to 100 req/s.  There are a couple more improvements I'm going to make, but I'm going to close this issue as done.  The fixes are available in the SNAPSHOT version as per: http://mock-server.com/where/maven_central.html#sonatype_snapshot
